SHELL := /bin/bash
.PHONY: figs 

figs: msprime_times.png \
      msprime_times_small.png \
      run_wf_neutral.speeds.png \
	  run_wf_neutral.speeds_perN.png \
      run_wf_selection.speeds_perN.png \
      run_spatial.speeds.png

include ../rules.mk
